openapi: 3.0.0
info:
  title: LanguageSloth
  description: An API for the development project of Antonia Langer, Alexander Dickbauer and Matthias Chory
  version: 1.0.0
servers:
- url: /
paths:
  /libretranslate:
    get:
      tags:
      - Get translation for text
      description: Retrieves the translation for a given text
      operationId: language_sloth_rest_libretranslate_get
      parameters:
        - name: text
          in: query
          description: text to translate
          required: true
          style: form
          explode: true
          schema:
            type: string
          examples:
            text:
              summary: Retrieve translation for a given text
              value: Hello World!
        - name: sourceLanguage
          in: query
          description: source language of the text
          required: true
          style: form
          explode: true
          schema:
            type: string
          examples:
            text:
              summary: source language of the text
              value: de
        - name: targetLanguage
          in: query
          description: target language of the text
          required: true
          style: form
          explode: true
          schema:
            type: string
          examples:
            text:
              summary: target language of the text
              value: en
      responses:
        "200":
          description: Translation was done successfully
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        "500":
          description: Translation failed
          content:
            text/plain:
              schema:
                type: string
                example: "Error 500: Internal Server Error - Reason"
                x-content-type: text/plain; charset=utf-8
      x-openapi-router-controller: swagger_server.controllers.libretranslate_get_controller
  /convertInputToWav:
    post:
      tags:
      - Convert input audio to WAV
      description: Converts input audio to WAV
      operationId: language_sloth_rest_convertInputToWav_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: Conversion to WAV was done successfully
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        "500":
          description: Conversion to WAV failed
          content:
            text/plain:
              schema:
                type: string
                example: "Error 500: Internal Server Error - Reason"
                x-content-type: text/plain; charset=utf-8
      x-openapi-router-controller: swagger_server.controllers.convertInputToWav_post_controller
components: {}

