openapi: 3.0.0
info:
  title: LanguageSloth
  description: An API for the development project of Antonia Langer, Alexander Dickbauer and Matthias Chory
  version: 1.0.0
servers:
- url: /
paths:
  /libretranslate:
    get:
      tags:
      - Get translation for text
      description: Retrieves the translation for a given text
      operationId: language_sloth_rest_libretranslate_get
      parameters:
      - name: text
        in: query
        description: text to translate
        required: true
        style: form
        explode: true
        schema:
          type: string
        examples:
          text:
            summary: Retrieve translation for a given text
            value: Hello World!
      responses:
        "200":
          description: Translation was done successfully
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain; charset=utf-8
        "500":
          description: Translation failed
          content:
            text/plain:
              schema:
                type: string
                example: "Error 500: Internal Server Error - Reason"
                x-content-type: text/plain; charset=utf-8
      x-openapi-router-controller: swagger_server.controllers.libretranslate_get_controller
components:
  schemas: {}

